# Generated by Django 5.2.1 on 2025-08-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Global low stock warning threshold')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow products to go into negative stock')),
                ('auto_adjust_on_sale', models.BooleanField(default=True, help_text='Automatically adjust stock when orders are completed')),
            ],
            options={
                'verbose_name': 'Stock Setting',
                'verbose_name_plural': 'Stock Settings',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Warning'), ('OUT_OF_STOCK', 'Out of Stock'), ('NEGATIVE_STOCK', 'Negative Stock Error')], max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('threshold', models.IntegerField(default=0, help_text='Stock level that triggered this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='store.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Manual Adjustment'), ('SALE', 'Sale'), ('RETURN', 'Return')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase from Supplier'), ('SALE', 'Product Sale'), ('DAMAGED', 'Damaged Goods'), ('EXPIRED', 'Expired Products'), ('MANUAL', 'Manual Adjustment'), ('RETURN', 'Customer Return'), ('INITIAL', 'Initial Stock'), ('CORRECTION', 'Stock Correction')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
